# Generated by Django 3.2.8 on 2021-10-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='documents/video')),
            ],
        ),
        migrations.CreateModel(
            name='MixAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file1', models.FileField(upload_to='documents/audio')),
                ('audio_file2', models.FileField(upload_to='documents/audio')),
            ],
        ),
        migrations.CreateModel(
            name='NoiseReduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='documents/audio')),
            ],
        ),
        migrations.CreateModel(
            name='Spectrogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='documents/audio')),
            ],
        ),
        migrations.AlterField(
            model_name='trimaudio',
            name='audio_file',
            field=models.FileField(upload_to='documents/audio'),
        ),
    ]
